# Generated by Django 3.2.3 on 2021-05-25 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Harakat', 'verbose_name_plural': 'Harakatlar'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Tarmoq', 'verbose_name_plural': 'Tarmoqlar'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Davlat', 'verbose_name_plural': 'Davlatlar'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Hamkor', 'verbose_name_plural': 'Hamkorlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Hisobot', 'verbose_name_plural': 'Hisobotlar'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Holat', 'verbose_name_plural': 'Holatlar'},
        ),
        migrations.AlterField(
            model_name='action',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.action'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.branch'),
        ),
        migrations.AlterField(
            model_name='report',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
